### ISSUE TITLE
Refactor Common Services branches

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#153]
AS AN Architect
I WANT Common Services branches to be refactored
SO THAT there would be no excess branches and folder structures in branches be correct

### Acceptance Criteria

- [ ] The scope is [`dev` branch of Common Services](https://github.com/buerokratt/Common-Services/tree/dev)
- [ ] `/DSL/Ruuter.public/` folder contains folder `/POST` for all of Ruuter's `POST` services
- [ ] `/DSL/Ruuter.public/` folder contains folder `/GET` for all of Ruuter's `GET` services
- [ ] `/DSL/Ruuter.private/` is deleted
- [ ] All refactored common services are moved to applicable DSL folders
- [ ] All legacy common services are moved to `/DSL/Ruuter.public/legacy/` folder

**Comment by matKlju** [comment]
[PR#154](https://github.com/buerokratt/Common-Services/pull/154)
