### ISSUE TITLE
Rahvaalgatus service

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Common-Services#29]
AS A Product Owner
I WANT TO have Rahvaalgatus service available in Bürokratt
SO THAT I can get information about Rahvaalgatus

### Acceptance Criteria

- [ ] End Client is able to get information about 5 most popular active initiatives (#75)

#### DSL

- [ ] #75
- [ ] #76

Information about API: https://rahvaalgatus.ee/api

**Comment by ValterAro** [comment]
One PR is merged and the other is still open currently (https://github.com/buerokratt/Common-Services/pull/27)

**Comment by ValterAro** [comment]
PR for the five latest public initatives (https://github.com/buerokratt/Common-Services/pull/27) and commit for the five most popular ongoing public initatives- https://github.com/buerokratt/Common-Services/commit/d7c1b5a900f90a5eff1190bdd0ae8004cac5b5be

**Comment by rasmusei** [comment]
New Epic created #77. Will close this on.
