### ISSUE TITLE
REST endpoint to retrieve national holidays in Estonia

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#60]
> [!NOTE]
> This is a sub-task of #59

AS AN Interested Party
I WANT TO have a REST endpoint to retrieve national holidays in Estonia
SO THAT I could use it for whatever reasons I want to

### Acceptance Criteria

- [x] `/calendar/national-holidays` to list all national holidays this given year
- [x] `/calendar/national-holidays/today` to validate if it's a national holiday today
- [x] `/calendar/national-holidays/previous` to provide the previous national holiday
- [x] `/calendar/national-holidays/next` to provide the next national holiday
- [x] `/calendar/national-holidays/ytd` to list all national holidays existed this given year until now (including)
- [x] `/calendar/national-holidays/eoy` to list all national holidays from today (including) until the end of given year
- [x] `/calendar/national-holidays/find/by-name` to list all national holidays based on input text
- [x] `/calendar/national-holidays/find/by-month` to list all national holidays based on month

#### DSL

- [x] Provide as Ruuter endpoints
- [x] Use Data Mapper where applicable
- [x] All output in `JSON`

#### Other

- [x] [Documentation](https://github.com/buerokratt/Common-Services/blob/feature-60/docs/example-queries/calendar/national-holidays.md) covering all endpoints, sample `curl` requests and their outputs
- [x] Use [feature branch](https://github.com/buerokratt/Common-Services/tree/feature-60) for development
- [x] Pull request / merge feature branch to [dev branch](https://github.com/buerokratt/Common-Services/tree/dev) when done with the mask

**Comment by jaX10bt** [comment]
Works as intended
