### ISSUE TITLE
Create a Ruuter service to link text input with national holidays common services

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#64]
> [!NOTE]
> This is a sub-issue of #63 and #60

AS A Product Owner
I WANT TO test if text input initiates applicable national holidays common services
SO THAT I could verify its intended functionality

### Acceptance Criteria

- [x] Every endpoint of #60 is triggered by 1 specific keyword
> E.g. "#prev_national_holiday" would trigger `/calendar/national-holidays/previous`
- [ ] All `#keywords` are hard-coded in Ruuter DSL `/calendar/national-holidays/search`
- [ ] Use [Ruuter's conditional switch](https://github.com/buerokratt/Ruuter/blob/dev/samples/steps/conditional-jump.md) functionality to trigger applicable endpoints based on input
- [ ] Based on triggering keyword, a request to an appropriate endpoint is made

#### DSL

- [ ] Service provided via Ruuter's `/calendar/national-holidays/search` endpoint

#### Example

**Request**

```
curl localhost:8080/calendar/national-holidays/search
   -H "Content-Type: application/json"
   -d '{"keyword": "#prev_national_holiday"}'
```

**Response**

```json
{
    "response": {
        "date": "2024-08-20",
        "name": "taasiseseisvumispäev"
    }
}
```

**Comment by matKlju** [comment]
https://github.com/buerokratt/Common-Services/issues/64

**Comment by matKlju** [comment]
Won't Do!
Issue has been solved by other technical solution
