### ISSUE TITLE
Rahvaalgatus service

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Common-Services#77]
AS A Product Owner
I WANT TO have Rahvaalgatus service available in Bürokratt
SO THAT I can get information about Rahvaalgatus

### Acceptance Criteria

- [x] End Client is able to get information about [5 most popular active initiatives](https://github.com/buerokratt/Common-Services/issues/75)
- [x] End Client is able to get information about [5 most recent active initiatives](https://github.com/buerokratt/Common-Services/issues/76)

#### DSL

- [x] #155
- [x] #75
- [x] #76

Information about API: https://rahvaalgatus.ee/api

**Comment by rasmusei** [comment]
Previous epic: #29

**Comment by matKlju** [comment]
Added Rahvaalgatus Services
[77-rahvaalgatus-service](https://github.com/buerokratt/Common-Services/tree/77-rahvaalgatus-service)

**Comment by matKlju** [comment]
Feature branch PR
#124 
[#126](https://github.com/buerokratt/Common-Services/pull/126)

**Comment by matKlju** [comment]
[#126](https://github.com/buerokratt/Common-Services/pull/126)

**Comment by matKlju** [comment]
Feature to dev:
https://github.com/buerokratt/Common-Services/pull/127/
https://github.com/buerokratt/Common-Services/pull/131

**Comment by matKlju** [comment]
Reopen, as NLU is not crated

**Comment by jaX10bt** [comment]
PR: https://github.com/buerokratt/Training-Module/pull/673

**Comment by ffrose** [comment]
PR: https://github.com/buerokratt/Training-Module/pull/682

**Comment by ffrose** [comment]
Service is working as intended.

Inputs:
Latest citizen initiatives: "Mis on viis viimast avalikku algatust?"
Most popular citizen initiatives: "Mis on hetkel populaarsemad rahvaalgatused?"
