### ISSUE TITLE
Statistics Estonia services

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Common-Services#78]
AS A Product Owner
I WANT TO have Statistics Estonia service available in Bürokratt
SO THAT I can get information about Statistics Estonia

### Acceptance Criteria

- [x] #79
- [ ] #196
- [x] #95
- [x] #94

**Comment by matKlju** [comment]
[PR#173](https://github.com/buerokratt/Common-Services/pull/173) issue #79

**Comment by ffrose** [comment]
Service is working as intended.

Inputs: 
Estimated subsistence minimum: "Arvestuslik elatusmiinimum"
Unemployment rate: "Mis on töötuse määr Eestis" & with value: "Mis oli töötuse määr aastal 2021 Eestis?"
Consumer price index:
"mis on tarbija indeks"
"mis oli tarbija indeks aastal 2021"
"mis oli tarbija indeks aastal 2021 jaanuaris?"
