### ISSUE TITLE
Common Service to get information about Parliament members participation statistics

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Common-Services#82]
> [!NOTE]
> This is a sub-issue of #81

AS A Service Manager
I WANT TO have a service to get information about Riigikogu members participation statistics
SO THAT End Clients could get this information for their chosen Riigikogu members

### Acceptance Criteria

- [x] The End Client gets information about specific Riigikogu member's participation statistics, providing their input in natural language
- [x] By default, statistics for the previous 30 days is provided
- [ ] The End Client can specify the period to get statistics for
- [ ] #188

#### NLU

- [ ] #187
- [x] Documentation provides full overview about sample NL requests to trigger the service via Bürokratt Chatbot

#### Service triggering

- [x] #189
- [x] #190
- [ ] Documentation provides sample queries to trigger the service as stand-alone
- [ ] Documentation provides sample queries to trigger the service via Bürokratt Chatbot

**Comment by matKlju** [comment]
Added service to Common-Services branch 
81-riigikogu-service

**Comment by matKlju** [comment]
https://github.com/buerokratt/Common-Services/pull/132
