### ISSUE TITLE
End Client is able to get information about most recent voting result

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Common-Services#83]
> [!NOTE]
> This is a sub-issue of #81

AS A Service manager
I WANT TO provide that the End Client is able to get information about most recent voting result
SO THAT I can provide that End Client is able to get information about most recent voting result

Acceptance Criteria

- [x] End Client is able to get information about most recent voting result. Result contain information about what was on voting and the result. /api/votings/last

**Comment by matKlju** [comment]
Added recent-voting service to
[81-riigikogu-service](https://github.com/buerokratt/Common-Services/tree/81-riigikogu-service)

**Comment by matKlju** [comment]
https://github.com/buerokratt/Common-Services/pull/135

**Comment by jaX10bt** [comment]
Works as intended
