### ISSUE TITLE
The End Client can get the highest electricity price of selected day

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Common-Services#86]
> [!NOTE]
> This is a sub-issue of #81

AS A Product Owner
I WANT he end client to be able to get the highest electricity price for a selected day
SO THAT hey can be informed about the electricity pricing trends for that day

Acceptance Criteria

- [x] The End Client can get the highest electricity price of selected day

**Comment by matKlju** [comment]
Added highest-price service for the current day

[80-electricity-service](https://github.com/buerokratt/Common-Services/tree/80-electricity-service)

Date can be specified.

*NB! The service uses a fixed +3 hour offset for Tallinn and doesn't adjust for Daylight Saving Time (DST)

**Comment by turnerrainer** [comment]
Code added straight to https://github.com/buerokratt/Common-Services/issues/80 without pull requests

**Comment by matKlju** [comment]
[PR #114](https://github.com/buerokratt/Common-Services/pull/114)

**Comment by jaX10bt** [comment]
Works as intended
